### ISSUE TITLE
Keyboard: Saved game name is empty

### ISSUE THREAD

**Issue by ouioui2003** [pleonex/Ninokuni#2]
Hello,

The keyboard work for the familiars name and i thank you for that. It's a great hack !

But the keyboard is used to add a name on the saved game at the begining, and the name is empty after validate it. Can you look that to correct this, please ?

And another thing: You can improve this game by doing a similar hack of fix_familiar_length (name with 7 chars instead of only 4) on the three ways the kerboard is used: The savedgame name could use 11 chars instead of only 6, and password when you catch the cauldron in bikini to 19 chars instead of 10. If you can know where that values are, it will be perfect to customize them.

Really cool that you share all that work with us !

aclamaciones

**Comment by pleonex** [comment]
Hi and thanks!

Yes, I am aware of that issue, it's because the game encode the name into the save file using the table from [keyboard/name_encoding.asm](https://github.com/pleonex/Ninokuni/blob/master/Assembly/keyboard/name_encoding.asm). I have to do some fixes to allow reading one & two bytes from that table, similar to the keyboard hack.

Regarding the enhancement you propose, can you open another issue so we can discuss it? Thanks :)

**Comment by Superfranci99** [comment]
I've just done a pull request to fix the routine which reads the player name from the sav. Now we just need to create a new table, maybe a complete one for all the translation projects.

**Comment by pleonex** [comment]
Closed with e1b534de66ca6c3b9715777adca9062a026c82f6 
The functions to encode and decode chars and strings have been fixed and the character are shown correctly.
